Repository iPlayed-games/backend, pull requests merged in 2023-08, with the labels that each got.

#16 5-prismORM installed
  README.md
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.ts
  src/database/mongo.test.ts
  src/database/mongo.ts
  src/server.ts
Labels: PR

#19 12-Controller and Router and services for users
  jest.config.ts
  package-lock.json
  package.json
  src/__test__/mongo.test.ts
  src/app.ts
  src/controller/userController.ts
  src/queries/user.ts
  src/routes/userRoute.ts
  src/services/userService.ts
  src/types/activity.ts
  src/types/user.ts
Labels: PR

#20 11-eslint-prettier
  .eslintrc.json
  .github/workflows/docker.yaml
  .gitignore
  .prettierrc.json
  README.md
  jest.config.ts
  package-lock.json
  package.json
  src/__test__/mongo.test.ts
  src/app.ts
  src/controller/userController.ts
  src/database/mongo.ts
  src/queries/user.ts
  src/routes/userRoute.ts
  src/server.ts
  src/services/userService.ts
  src/types/activity.ts
  src/types/user.ts
  tsconfig.json
Labels: PR

#23 13 database schema and seed
  prisma/client.ts
  prisma/mock-data.ts
  prisma/schema.prisma
  src/queries/user.ts
  src/services/userService.ts
Labels: PR

#28 32-lint-format-test
  .eslintrc.json
  .github/workflows/cicd.yaml
  .github/workflows/docker.yaml
  package.json
Labels: update, requireFrontEnd

#29 27 update prisma and seed
  prisma/client.ts
  prisma/mock-data.ts
  prisma/schema.prisma
  src/types/activity.ts
  src/types/enumCategory.ts
  src/types/location.ts
  src/types/user.ts
  src/types/venue.ts
  tsconfig.json
Labels: PR

#30 26-seed data from once and cleaning
  .env-template
  .github/workflows/cicd.yaml
  package.json
  prisma/client.ts
  prisma/mock-data.ts
  prisma/schema.prisma
  src/__test__/mongo.test.ts
  src/config/mongo/mongo.ts
  src/config/prisma/prisma-client.ts
  src/data/mock-data.ts
  src/server.ts
  src/services/userService.ts
  src/types/activity.ts
  src/types/enumCategory.ts
  src/types/location.ts
  src/types/user.ts
  src/types/venue.ts
  src/utils/shutdown-server.ts
  tsconfig.json
Labels: PR

#33 fix: readme.md added
  README.md
Labels: PR

#34 31- array of category changed
  prisma/schema.prisma
  src/config/prisma/prisma-client.ts
  src/data/mock-data.ts
  src/types/venue.ts
Labels: PR

#37 37- Controller, service and router created
  src/app.ts
  src/config/prisma/prisma-client.ts
  src/controller/venueController.ts
  src/routes/venueRoute.ts
  src/services/venueService.ts
Labels: PR

#39 32-Refactor-Data
  src/config/prisma/prisma-client.ts
  src/data/mock-data.ts
  src/queries/user.ts
Labels: PR

#42 36-create-adding e2e test package
  .github/workflows/cicd.yaml
  .gitignore
  package-lock.json
  package.json
  src/__test__/mongo.test.ts
  src/__test__/users-router.test.ts
Labels: PR

#44 35-Create-Controller-And-Services-for-Auth(user)
  .github/workflows/cicd.yaml
  README.md
  src/app.ts
  src/config/swagger/docs.yaml
  src/config/swagger/swagger-ui.ts
  src/controller/authController.ts
  src/controller/venueController.ts
  src/queries/user.ts
  src/routes/authRoute.ts
  src/services/authService.ts
  src/services/venueService.ts
  src/utils/converter-json-yaml.ts
Labels: PR

#46 24-create Swagger UI
  README.md
  src/__test__/swagger.test.ts
  src/config/swagger/docs.yaml
Labels: PR

#47 41 return type for get venue by
  src/services/venueService.ts
Labels: PR

#49 Bug: 40-Venus-Service-Must-Include-Activities
  src/queries/queries.ts
  src/services/userService.ts
  src/services/venueService.ts
Labels: bug

#51 45-Install Husky run lint before commit
  .husky/pre-commit
  package-lock.json
  package.json
Labels: ticket

#50 48 path tsconfig
  jest.config.ts
  src/__test__/mongo.test.ts
  src/__test__/swagger.test.ts
  src/app.ts
  src/config/prisma/prisma-client.ts
  src/config/swagger/swagger-ui.ts
  src/controller/authController.ts
  src/controller/userController.ts
  src/controller/venueController.ts
  src/data/mock-data.ts
  src/routes/authRoute.ts
  src/routes/userRoute.ts
  src/routes/venueRoute.ts
  src/server.ts
  src/services/authService.ts
  src/services/userService.ts
  src/services/venueService.ts
  src/typing/activity.ts
  src/typing/enumCategory.ts
  src/typing/location.ts
  src/typing/user.ts
  src/typing/venue.ts
  tsconfig.json
Labels: PR

#54 hotfix: before paths
  jest.config.ts
  package-lock.json
  package.json
  src/__test__/mongo.test.ts
  src/__test__/swagger.test.ts
  src/app.ts
  src/config/prisma/prisma-client.ts
  src/config/swagger/swagger-ui.ts
  src/controller/authController.ts
  src/controller/userController.ts
  src/controller/venueController.ts
  src/data/mock-data.ts
  src/routes/authRoute.ts
  src/routes/userRoute.ts
  src/routes/venueRoute.ts
  src/server.ts
  src/services/authService.ts
  src/services/userService.ts
  src/services/venueService.ts
  tsconfig.json
Labels: PR
